DATA_ACQUISTION_DATE   = '2025_01_15'
RAW_DATA_FOLDER        = f"../RAW_DATA/{DATA_ACQUISTION_DATE}"
EXTRACTED_DATA_FOLDER  = f"../EXTRACTED_DATA/{DATA_ACQUISTION_DATE}"
DATABASE               = f"{EXTRACTED_DATA_FOLDER}/{DATA_ACQUISTION_DATE}_data-extracted.db"

SEARCH_DATA_TABLE           = f"../SRA_SEARCH_TABLE/{DATA_ACQUISTION_DATE}/SRA_search_table-{DATA_ACQUISTION_DATE}.parquet"
PRIMARY_DATA_TABLES_FOLDER  = "./PRIMARY_DATA_TABLES"
ASSEMBLY_DATA_TABLES_FOLDER = "./ASSEMBLY_RESULTS" 

ANALYSIS_DATA_FOLDER   = './ANALYSIS_DATA'
PIPELINE_RESULTS       = f"{ANALYSIS_DATA_FOLDER}/pipeline-individual_assemblies.parquet"
LOGAN_RESULTS          = f"{ANALYSIS_DATA_FOLDER}/logan_screen_results.parquet"

PUBLICATION_DATA_FOLDER = './PUBLICATION_DATA'